apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      planet: hello
    replicas: 1
    template:
      metadata:
        labels:
          planet: hello
      spec:
        containers:
          - name: hello-world
            image: ko://github.com/vickynarang01/helloworld
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080
            env:
              - name: PORT
                value: '8080'

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    planet: hello
  ports:
    - port: 8080
